// This program calculates the total weighted utility from the itemset generated by SyntheticData.c.
// Going forward, this program should be able to find groupings from categories that pass the first test, and make pairings of two and up.

#include <stdio.h>
#include <stdlib.h>



int main(int argc, char* argv[])
{
	FILE *myFile;
	myFile = fopen("Medium10.txt", "r");

	int i;
	int overallRating[1000];
	int quality[1000];
	int price[1000];
	int time[1000];
	int userInterface[1000];
	int design[1000];
	int color[1000];
    int material[1000];
    int name[1000];
    int origin[1000];
    int safety[1000];
    int age[1000];
    int repair[1000];


    int totalWeightedUtility[1000];



    int qualityWU = 0;
	int priceWU = 0;
	int timeWU = 0;
	int userInterfaceWU = 0;
	int designWU = 0;
	int colorWU = 0;
    int materialWU = 0;
    int nameWU = 0;
    int originWU = 0;
    int safetyWU = 0;
    int ageWU = 0;
    int repairWU = 0;

	if (myFile == NULL)
    {
        printf("Error Reading File\n");
        exit (0);
    }
    for (i = 0; i < 1000; i++)
    {
        fscanf(myFile, " %d %d %d %d %d %d %d %d %d %d %d %d %d", &overallRating[i], &quality[i], &price[i], &time[i],
         &userInterface[i], &design[i], &color[i], &material[i], &name[i], &origin[i], &safety[i], &age[i], &repair[i]);

    }

    fclose(myFile);

    for(i=0; i<1000; i++){
    	totalWeightedUtility[i] = overallRating[i] * (quality[i] + price[i] 
+ time[i] + userInterface[i] + design[i] + color[i] + material[i] + name[i] + origin[i] + safety[i] + age[i] + repair[i]);

    	if(quality[i] > 0){
    		qualityWU += totalWeightedUtility[i];
    	}
    	if(price[i] > 0){
    		priceWU += totalWeightedUtility[i];
    	}
    	if(time[i] > 0){
    		timeWU += totalWeightedUtility[i];
    	}
    	if(userInterface[i] > 0){
    		userInterfaceWU += totalWeightedUtility[i];
    	}
    	if(design[i] > 0){
    		designWU += totalWeightedUtility[i];
    	}
    	if(color[i] > 0){
    		colorWU += totalWeightedUtility[i];
    	}
        if(material[i] > 0){
            materialWU += totalWeightedUtility[i];
        }
        if(name[i] > 0){
            nameWU += totalWeightedUtility[i];
        }
        if(origin[i] > 0){
            originWU += totalWeightedUtility[i];
        }
        if(safety[i] > 0){
            safetyWU += totalWeightedUtility[i];
        }
        if(age[i] > 0){
            ageWU += totalWeightedUtility[i];
        }
        if(repair[i] > 0){
            repairWU += totalWeightedUtility[i];
        }


    }

    printf("\nSingles\n");

    printf("Quality WU: %d\n", qualityWU);
    printf("Price WU: %d\n", priceWU);
    printf("Time WU: %d\n", timeWU);
    printf("UserInterface WU: %d\n", userInterfaceWU);
    printf("Design WU: %d\n", designWU);
    printf("Color WU: %d\n", colorWU);
    printf("Material WU: %d\n", materialWU);
    printf("Name WU: %d\n", nameWU);
    printf("Origin WU: %d\n", originWU);
    printf("Safety WU: %d\n", safetyWU);
    printf("Age WU: %d\n", ageWU);
    printf("Repair WU: %d\n", repairWU);

    //With Threshold 27000, only UserInterface, Design, and Color are dropped

    printf("\nDoubles\n");

    int qpWU = 0;
    int qtWU = 0;
    int qmWU = 0;
    int qnWU = 0;
    int qoWU = 0;
    int qsWU = 0;
    int qaWU = 0;
    int qrWU = 0;

    int ptWU = 0;
    int pmWU = 0;
    int pnWU = 0;
    int poWU = 0;
    int psWU = 0;
    int paWU = 0;
    int prWU = 0;

    int tmWU = 0;
    int tnWU = 0;
    int toWU = 0;
    int tsWU = 0;
    int taWU = 0;
    int trWU = 0;

    int mnWU = 0;
    int moWU = 0;
    int msWU = 0;
    int maWU = 0;
    int mrWU = 0;

    int noWU = 0;
    int nsWU = 0;
    int naWU = 0;
    int nrWU = 0;

    int osWU = 0;
    int oaWU = 0;
    int orWU = 0;

    int saWU = 0;
    int srWU = 0;

    int arWU = 0;

    for(i=0; i<1000; i++){
        if(quality[i] > 0 && price[i] > 0){
            qpWU += totalWeightedUtility[i];
        }
        if(quality[i] > 0 && time[i] > 0){
            qtWU += totalWeightedUtility[i];
        }
        if(quality[i] > 0 && material[i] > 0){
            qmWU += totalWeightedUtility[i];
        }
        if(quality[i] > 0 && name[i] > 0){
            qnWU += totalWeightedUtility[i];
        }
        if(quality[i] > 0 && origin[i] > 0){
            qoWU += totalWeightedUtility[i];
        }
        if(quality[i] > 0 && safety[i] > 0){
            qsWU += totalWeightedUtility[i];
        }
        if(quality[i] > 0 && age[i] > 0){
            qaWU += totalWeightedUtility[i];
        }
        if(quality[i] > 0 && repair[i] > 0){
            qrWU += totalWeightedUtility[i];
        }

        if(price[i] > 0 && time[i] > 0){
            ptWU += totalWeightedUtility[i];
        }
        if(price[i] > 0 && material[i] > 0){
            pmWU += totalWeightedUtility[i];
        }
        if(price[i] > 0 && name[i] > 0){
            pnWU += totalWeightedUtility[i];
        }
        if(price[i] > 0 && origin[i] > 0){
            poWU += totalWeightedUtility[i];
        }
        if(price[i] > 0 && safety[i] > 0){
            psWU += totalWeightedUtility[i];
        }
        if(price[i] > 0 && age[i] > 0){
            paWU += totalWeightedUtility[i];
        }
        if(price[i] > 0 && repair[i] > 0){
            prWU += totalWeightedUtility[i];
        }

        if(time[i] > 0 && material[i] > 0){
            tmWU += totalWeightedUtility[i];
        }
        if(time[i] > 0 && name[i] > 0){
            tnWU += totalWeightedUtility[i];
        }
        if(time[i] > 0 && origin[i] > 0){
            toWU += totalWeightedUtility[i];
        }
        if(time[i] > 0 && safety[i] > 0){
            tsWU += totalWeightedUtility[i];
        }
        if(time[i] > 0 && age[i] > 0){
            taWU += totalWeightedUtility[i];
        }
        if(time[i] > 0 && repair[i] > 0){
            trWU += totalWeightedUtility[i];
        }

        if(material[i] > 0 && name[i] > 0){
            mnWU += totalWeightedUtility[i];
        }
        if(material[i] > 0 && origin[i] > 0){
            moWU += totalWeightedUtility[i];
        }
        if(material[i] > 0 && safety[i] > 0){
            msWU += totalWeightedUtility[i];
        }
        if(material[i] > 0 && age[i] > 0){
            maWU += totalWeightedUtility[i];
        }
        if(material[i] > 0 && repair[i] > 0){
            mrWU += totalWeightedUtility[i];
        }

        if(name[i] > 0 && origin[i] > 0){
            noWU += totalWeightedUtility[i];
        }
        if(name[i] > 0 && safety[i] > 0){
            nsWU += totalWeightedUtility[i];
        }
        if(name[i] > 0 && age[i] > 0){
            naWU += totalWeightedUtility[i];
        }
        if(name[i] > 0 && repair[i] > 0){
            nrWU += totalWeightedUtility[i];
        }

        if(origin[i] > 0 && safety[i] > 0){
            osWU += totalWeightedUtility[i];
        }
        if(origin[i] > 0 && age[i] > 0){
            oaWU += totalWeightedUtility[i];
        }
        if(origin[i] > 0 && repair[i] > 0){
            orWU += totalWeightedUtility[i];
        }

        if(safety[i] > 0 && age[i] > 0){
            saWU += totalWeightedUtility[i];
        }
        if(safety[i] > 0 && repair[i] > 0){
            srWU += totalWeightedUtility[i];
        }

        if(age[i] > 0 && repair[i] > 0){
            arWU += totalWeightedUtility[i];
        }
    }


    printf("Quality and Price WU: %d\n", qpWU);
    printf("Quality and Time WU: %d\n", qtWU);
    printf("Quality and Material WU: %d\n", qmWU);
    printf("Quality and Name WU: %d\n", qnWU);
    printf("Quality and Origin WU: %d\n", qoWU);
    printf("Quality and Safety WU: %d\n", qsWU);
    printf("Quality and Age WU: %d\n", qaWU);
    printf("Quality and Repair WU: %d\n", qrWU);

    printf("Price and Time WU: %d\n", ptWU);
    printf("Price and Material WU: %d\n", pmWU);
    printf("Price and Name WU: %d\n", pnWU);
    printf("Price and Origin WU: %d\n", poWU);
    printf("Price and Safety WU: %d\n", psWU);
    printf("Price and Age WU: %d\n", paWU);
    printf("Price and Repair WU: %d\n", prWU);

    printf("Time and Material WU: %d\n", tmWU);
    printf("Time and Name WU: %d\n", tnWU);
    printf("Time and Origin WU: %d\n", toWU);
    printf("Time and Safety WU: %d\n", tsWU);
    printf("Time and Age WU: %d\n", taWU);
    printf("Time and Repair WU: %d\n", trWU);

    printf("Material and Name WU: %d\n", mnWU);
    printf("Material and Origin WU: %d\n", moWU);
    printf("Material and Safety WU: %d\n", msWU);
    printf("Material and Age WU: %d\n", maWU);
    printf("Material and Repair WU: %d\n", mrWU);

    printf("Name and Origin WU: %d\n", noWU);
    printf("Name and Safety WU: %d\n", nsWU);
    printf("Name and Age WU: %d\n", naWU);
    printf("Name and Repair WU: %d\n", nrWU);

    printf("Origin and Safety WU: %d\n", osWU);
    printf("Origin and Age WU: %d\n", oaWU);
    printf("Origin and Repair WU: %d\n", orWU);

    printf("Safety and Age WU: %d\n", saWU);
    printf("Safety and Repair WU: %d\n", srWU);

    printf("Age and Repair WU: %d\n", arWU);


    //P N S A R

    printf("\nTriples\n");

    int pnsWU = 0;
    int pnaWU = 0;
    int pnrWU = 0;
    int psaWU = 0;
    int psrWU = 0;
    int parWU = 0;
    int nsaWU = 0;

    int nsrWU = 0;
    int narWU = 0;
    int sarWU = 0;

    int qpnWU = 0;
    int qprWU = 0;
    int qnrWU = 0;

    for(i = 0; i<1000; i++){
        if(price[i] > 0 && name[i] > 0 && safety[i] > 0){
            pnsWU += totalWeightedUtility[i];
        }
        if(price[i] > 0 && name[i] > 0 && age[i] > 0){
            pnaWU += totalWeightedUtility[i];
        }
        if(price[i] > 0 && name[i] > 0 && repair[i] > 0){
            pnrWU += totalWeightedUtility[i];
        }

        if(price[i] > 0 && safety[i] > 0 && age[i] > 0){
            psaWU += totalWeightedUtility[i];
        }
        if(price[i] > 0 && safety[i] > 0 && repair[i] > 0){
            psrWU += totalWeightedUtility[i];
        }

        if(price[i] > 0 && age[i] > 0 && repair[i] > 0){
            parWU += totalWeightedUtility[i];
        }

        if(name[i] > 0 && safety[i] > 0 && age[i] > 0){
            nsaWU += totalWeightedUtility[i];
        }
        if(name[i] > 0 && safety[i] > 0 && repair[i] > 0){
            nsrWU += totalWeightedUtility[i];
        }

        if(name[i] > 0 && age[i] > 0 && repair[i] > 0){
            narWU += totalWeightedUtility[i];
        }

        if(safety[i] > 0 && age[i] > 0 && repair[i] > 0){
            sarWU += totalWeightedUtility[i];
        }
        if(quality[i] > 0 && price[i] > 0 && name[i] > 0){
            qpnWU += totalWeightedUtility[i];
        }
        if(quality[i] > 0 && price[i] > 0 && repair[i] > 0){
            qprWU += totalWeightedUtility[i];
        }
        if(quality[i] > 0 && name[i] > 0 && repair[i] > 0){
            qnrWU += totalWeightedUtility[i];
        }
    }

    printf("Price, Name, Safety: %d\n", pnsWU);
    printf("Price, Name, Age: %d\n", pnaWU);
    printf("Price, Name, Repair: %d\n", pnrWU);
    printf("Price, Safety, Age: %d\n", psaWU);
    printf("Price, Safety, Repair: %d\n", psrWU);
    printf("Price, Age, Repair: %d\n", parWU);
    printf("Name, Safety, Age: %d\n", nsaWU);
    printf("Name, Safety, Repair: %d\n", nsrWU);
    printf("Name, Age, Repair: %d\n", narWU);
    printf("Safety, Age, Repair: %d\n", sarWU);

    printf("Quality, Price, Name: %d\n", qpnWU);
    printf("Quality, Price, Repair: %d\n", qprWU);
    printf("Quality, Name, Repair: %d\n", qnrWU);

   

}